name: C Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SDL2 libraries
        run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - name: Build the project
        run: gcc -o BrickBreaker *.c -lSDL2 -lSDL2_image -lSDL2_ttf

      - name: Copy necessary files
        run: |
          mkdir temp
          cp BrickBreaker temp/
          cp -r resources temp/
          cp /usr/lib/x86_64-linux-gnu/libSDL2*.so* temp/

      - name: Create zip file
        run: zip -r BrickBreaker.zip temp/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BrickBreaker
          path: BrickBreaker.zip